import Phaser from 'phaser'; import './style.css'; import {TEAMS,POS} from './data.js';
const W=1200,H=720, FIELD={l:45,r:1155,t:55,b:665,cy:360,goalTop:285,goalBottom:435};
const CFG={era:2002,home:0,away:1,mode:1,diff:'보통'};
const diffMul={쉬움:.72,보통:.9,어려움:1.05,월드클래스:1.18};
class Menu extends Phaser.Scene{constructor(){super('menu')}create(){this.cameras.main.setBackgroundColor('#07111b');this.add.text(W/2,105,'WORLD FOOTBALL LEGENDS',{fontSize:'58px',fontStyle:'bold',color:'#fff'}).setOrigin(.5);this.add.text(W/2,165,'6 VS 6 · 2002 / 2006 / 2012',{fontSize:'22px',color:'#9fc5d8'}).setOrigin(.5);this.add.text(W/2,220,'시대',{fontSize:'18px',color:'#fff'}).setOrigin(.5);[2002,2006,2012].forEach((e,i)=>this.button(430+i*170,265,String(e),()=>{CFG.era=e;this.scene.restart()}));let teams=TEAMS[CFG.era];this.add.text(W/2,325,'내 팀',{fontSize:'18px'}).setOrigin(.5);teams.forEach((t,i)=>this.button(170+(i%4)*290,370+Math.floor(i/4)*58,`${t[2]} ${t[1]}`,()=>{CFG.home=i;this.scene.restart()},i===CFG.home));this.add.text(W/2,495,'상대 팀',{fontSize:'18px'}).setOrigin(.5);teams.forEach((t,i)=>this.button(170+(i%4)*290,540+Math.floor(i/4)*58,`${t[2]} ${t[1]}`,()=>{CFG.away=i;this.scene.restart()},i===CFG.away));this.button(W/2,675,'경기 시작',()=>this.scene.start('match'),true)}button(x,y,s,fn,on=false){let b=this.add.text(x,y,s,{fontSize:'18px',backgroundColor:on?'#25764e':'#17324a',padding:{x:16,y:9},color:'#fff'}).setOrigin(.5).setInteractive({useHandCursor:true});b.on('pointerdown',fn)}}
class Match extends Phaser.Scene{constructor(){super('match')}create(){this.score=[0,0];this.timeLeft=90;this.players=[];this.owner=null;this.ballVel=new Phaser.Math.Vector2();this.keys=this.input.keyboard.addKeys('W,A,S,D,J,K,L,Q,SPACE');this.createPitch();this.createTeams();this.ball=this.add.circle(W/2,H/2,9,0xffffff).setStrokeStyle(2,0x17212b).setDepth(4);this.hud=this.add.text(W/2,15,'',{fontSize:'24px',fontStyle:'bold'}).setOrigin(.5,0).setDepth(10);this.tip=this.add.text(18,16,'WASD 이동 · Q 전환 · J 패스/태클 · K 슛 · SPACE 대시',{fontSize:'14px',color:'#d5e5ef'}).setDepth(10);this.msg=this.add.text(W/2,92,'',{fontSize:'34px',fontStyle:'bold'}).setOrigin(.5).setDepth(10);this.lastJ=false;this.lastK=false;this.lastQ=false;}
createPitch(){let g=this.add.graphics();g.fillStyle(0x21894d).fillRect(0,0,W,H);for(let i=0;i<10;i++){if(i%2)g.fillStyle(0x238f50).fillRect(i*W/10,0,W/10,H)}g.lineStyle(4,0xe8fff0).strokeRect(FIELD.l,FIELD.t,FIELD.r-FIELD.l,FIELD.b-FIELD.t).lineBetween(W/2,FIELD.t,W/2,FIELD.b).strokeCircle(W/2,H/2,88).strokeRect(FIELD.l,210,150,300).strokeRect(FIELD.r-150,210,150,300);g.fillStyle(0xdce6ea).fillRect(16,FIELD.goalTop,29,150).fillRect(FIELD.r,FIELD.goalTop,29,150)}
createTeams(){const starts=[[90,250,250,430,430,545],[1110,950,950,770,770,655]], ys=[360,235,485,225,495,360];for(let team=0;team<2;team++){let data=TEAMS[CFG.era][team?CFG.away:CFG.home];data[3].forEach((name,i)=>{let p={team,i,name,x:starts[team][i],y:ys[i],baseX:starts[team][i],baseY:ys[i],state:'SHAPE',hold:0,cool:0,st:100};p.body=this.add.circle(p.x,p.y,17,team?0x3975df:0xe44f4f).setDepth(3);p.label=this.add.text(p.x,p.y-29,name,{fontSize:'11px',color:'#fff',stroke:'#000',strokeThickness:3}).setOrigin(.5).setDepth(5);this.players.push(p)})}this.active=5;}
update(_,ms){let dt=Math.min(ms/1000,.03);this.timeLeft-=dt;if(this.timeLeft<=0){this.scene.start('menu');return}let q=this.keys.Q.isDown,j=this.keys.J.isDown,k=this.keys.K.isDown;if(q&&!this.lastQ)this.switchPlayer();this.lastQ=q;this.human(dt);if(j&&!this.lastJ)this.actionPassTackle();this.lastJ=j;if(k&&!this.lastK)this.shoot(this.active);this.lastK=k;this.players.forEach((p,idx)=>{p.cool=Math.max(0,p.cool-dt);if(idx!==this.active)this.ai(p,idx,dt)});this.updateBall(dt);this.goalCheck();this.players.forEach(p=>{p.body.setPosition(p.x,p.y);p.label.setPosition(p.x,p.y-29)});let h=TEAMS[CFG.era][CFG.home],a=TEAMS[CFG.era][CFG.away];this.hud.setText(`${h[2]} ${h[0]}  ${this.score[0]} : ${this.score[1]}  ${a[0]} ${a[2]}     ${Math.ceil(this.timeLeft)}초`)}
human(dt){let p=this.players[this.active];let dx=(this.keys.D.isDown?1:0)-(this.keys.A.isDown?1:0),dy=(this.keys.S.isDown?1:0)-(this.keys.W.isDown?1:0),m=Math.hypot(dx,dy)||1;let sp=this.keys.SPACE.isDown&&p.st>0?245:175;p.st=Phaser.Math.Clamp(p.st+(this.keys.SPACE.isDown?-28:12)*dt,0,100);p.x+=dx/m*sp*dt;p.y+=dy/m*sp*dt;this.clamp(p)}
switchPlayer(){let candidates=this.players.map((p,i)=>({p,i})).filter(o=>o.p.team===0&&o.p.i!==0).sort((a,b)=>this.dist(a.p,this.ball)-this.dist(b.p,this.ball));this.active=candidates.find(o=>o.i!==this.active)?.i??this.active}
actionPassTackle(){let p=this.players[this.active];if(this.owner===this.active){this.pass(this.active);return}if(this.owner!==null&&this.players[this.owner].team===1&&this.dist(p,this.players[this.owner])<52){if(Math.random()<.68){this.owner=this.active;this.say('태클 성공')}else this.say('태클 실패')}}
ai(p,idx,dt){let own=this.owner===null?null:this.players[this.owner],dir=p.team===0?1:-1;let target={x:p.baseX,y:p.baseY},speed=145*(p.team?diffMul[CFG.diff]:.9);if(p.i===0){this.goalkeeperAI(p,idx,own,dt);return}if(own&&own.i===0){if(own.team===p.team){ // GK possession: teammates fan out
 let depth=[0,120,120,255,255,390][p.i];target.x=own.x+dir*depth;target.y=p.baseY+(p.i%2? -25:25);
 }else{ // opponent GK possession: retreat and mark outlets, never swarm keeper
 let retreat=own.team===0?W*.58:W*.42;target.x=p.team===0?Math.min(p.baseX+160,retreat):Math.max(p.baseX-160,retreat);let outlet=this.nearestOpponentOutlet(p.team,p);if(outlet)target.y=Phaser.Math.Linear(p.baseY,outlet.y,.42);
 }}else if(own&&own.team===p.team){if(idx===this.owner){let enemy=this.nearestEnemy(p);target.x=p.x+dir*170;target.y=Phaser.Math.Clamp(p.y+(enemy&&this.dist(p,enemy)<105?(p.y<enemy.y?-95:95):Math.sin(this.time.now/550+p.i)*28),75,H-75)}else{let depth=[0,-120,-120,55,55,190][p.i];target.x=own.x+dir*depth;target.y=Phaser.Math.Clamp(H/2+(p.i%2?-150:150)+(own.y-H/2)*.38,80,H-80)}}else if(own&&own.team!==p.team){let press=this.closestFieldPlayer(p.team,own);if(press===p)target={x:own.x-dir*22,y:own.y};else{let mark=this.nearestOpponentOutlet(p.team,p);target.x=p.baseX+(own.x-W/2)*.32;target.y=mark?Phaser.Math.Linear(p.baseY,mark.y,.48):p.baseY}}else{let chaser=this.closestFieldPlayer(p.team,this.ball);if(chaser===p)target={x:this.ball.x+this.ballVel.x*.18,y:this.ball.y+this.ballVel.y*.18};else{target.x=p.baseX+(this.ball.x-W/2)*.28;target.y=p.baseY+(this.ball.y-H/2)*.25}}this.move(p,target,speed,dt);if(this.owner===idx){let gx=p.team?FIELD.l:FIELD.r;if(Math.abs(gx-p.x)<290)this.shoot(idx);else if(this.nearestEnemy(p)&&this.dist(p,this.nearestEnemy(p))<75&&Math.random()<.045)this.pass(idx)}}
goalkeeperAI(p,idx,own,dt){let dir=p.team===0?1:-1,goalX=p.team===0?82:1118;if(this.owner===idx){p.hold+=dt; // controlled distribution state
 let target={x:goalX,y:Phaser.Math.Clamp(p.y,310,410)};this.move(p,target,95,dt);if(p.hold>.8){let receiver=this.bestGKReceiver(p);if(receiver&&this.safety(receiver,p.team)>75)this.throwTo(idx,receiver);else if(p.hold>1.35)this.longKick(idx);}}else{p.hold=0;let tx=goalX,ty=Phaser.Math.Clamp(this.ball.y,300,420);if(this.owner===null&&this.dist(p,this.ball)<115){tx=this.ball.x;ty=this.ball.y}this.move(p,{x:tx,y:ty},125,dt);if(this.owner===null&&this.dist(p,this.ball)<25){this.owner=idx;this.ballVel.set(0);this.say('GK 캐치')}}}
bestGKReceiver(gk){let mates=this.players.filter(p=>p.team===gk.team&&p.i>0&&p.i<5);return mates.sort((a,b)=>{let sa=this.safety(a,gk.team)+(gk.team===0?a.x:-a.x)*.08,sb=this.safety(b,gk.team)+(gk.team===0?b.x:-b.x)*.08;return sb-sa})[0]}
safety(p,team){return Math.min(...this.players.filter(e=>e.team!==team&&e.i!==0).map(e=>this.dist(p,e)))}
throwTo(idx,t){let p=this.players[idx];this.owner=null;let v=new Phaser.Math.Vector2(t.x-p.x,t.y-p.y).normalize().scale(455);this.ballVel.copy(v);p.hold=0;this.say('GK 던지기')}
longKick(idx){let p=this.players[idx],fw=this.players[p.team*6+5];this.owner=null;let v=new Phaser.Math.Vector2(fw.x+(p.team===0?150:-150)-p.x,fw.y-p.y).normalize().scale(610);this.ballVel.copy(v);p.hold=0;this.say('GK 롱킥')}
pass(idx){if(this.owner!==idx)return;let p=this.players[idx],mates=this.players.filter(q=>q.team===p.team&&q.i!==0&&q!==p);let dir=p.team===0?1:-1;mates.sort((a,b)=>((b.x-a.x)*dir)+this.safety(b,p.team)*.7-this.safety(a,p.team)*.7);let t=mates[0];if(!t)return;this.owner=null;this.ballVel.set(t.x-p.x,t.y-p.y).normalize().scale(440)}
shoot(idx){if(this.owner!==idx)return;let p=this.players[idx],gx=p.team===0?W+10:-10,gy=H/2+Phaser.Math.Between(-70,70);this.owner=null;this.ballVel.set(gx-p.x,gy-p.y).normalize().scale(650)}
updateBall(dt){if(this.owner!==null){let p=this.players[this.owner];this.ball.setPosition(p.x+(p.team===0?20:-20),p.y);return}this.ball.x+=this.ballVel.x*dt;this.ball.y+=this.ballVel.y*dt;this.ballVel.scale(Math.pow(.985,dt*60));if(this.ball.y<FIELD.t||this.ball.y>FIELD.b){this.ball.y=Phaser.Math.Clamp(this.ball.y,FIELD.t,FIELD.b);this.ballVel.y*=-.7}for(let i=0;i<this.players.length;i++){if(this.dist(this.players[i],this.ball)<22){this.owner=i;this.ballVel.set(0);break}}}
goalCheck(){if(this.ball.x<0||this.ball.x>W){if(this.ball.y>FIELD.goalTop&&this.ball.y<FIELD.goalBottom){let t=this.ball.x>W?0:1;this.score[t]++;this.say('GOAL!');this.resetPositions()}else{this.ball.x=Phaser.Math.Clamp(this.ball.x,5,W-5);this.ballVel.x*=-.6}}}
resetPositions(){this.owner=null;this.ball.setPosition(W/2,H/2);this.ballVel.set(0);this.players.forEach(p=>{p.x=p.baseX;p.y=p.baseY;p.hold=0})}
closestFieldPlayer(team,o){return this.players.filter(p=>p.team===team&&p.i!==0).sort((a,b)=>this.dist(a,o)-this.dist(b,o))[0]}
nearestEnemy(p){return this.players.filter(e=>e.team!==p.team&&e.i!==0).sort((a,b)=>this.dist(a,p)-this.dist(b,p))[0]}
nearestOpponentOutlet(team,p){return this.players.filter(e=>e.team!==team&&e.i!==0).sort((a,b)=>Math.abs(a.y-p.y)-Math.abs(b.y-p.y))[0]}
move(p,t,s,dt){let dx=t.x-p.x,dy=t.y-p.y,m=Math.hypot(dx,dy);if(m>4){let ease=Math.min(1,m/65);p.x+=dx/m*s*ease*dt;p.y+=dy/m*s*ease*dt}this.clamp(p)}
clamp(p){p.x=Phaser.Math.Clamp(p.x,FIELD.l+18,FIELD.r-18);p.y=Phaser.Math.Clamp(p.y,FIELD.t+18,FIELD.b-18)}dist(a,b){return Phaser.Math.Distance.Between(a.x,a.y,b.x,b.y)}say(s){this.msg.setText(s);this.time.delayedCall(800,()=>this.msg.setText(''))}}
new Phaser.Game({type:Phaser.AUTO,width:W,height:H,parent:'game',backgroundColor:'#07111b',scene:[Menu,Match],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
